(function() {var implementors = {};
implementors["actix_web"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"actix_web/error/struct.InternalError.html\" title=\"struct actix_web::error::InternalError\">InternalError</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> + 'static,&nbsp;</span>",synthetic:false,types:["actix_web::error::InternalError"]},];
implementors["failure"] = [];
implementors["syncstorage"] = [{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"syncstorage/error/struct.ApiError.html\" title=\"struct syncstorage::error::ApiError\">ApiError</a>",synthetic:false,types:["syncstorage::error::ApiError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"syncstorage/db/error/struct.DbError.html\" title=\"struct syncstorage::db::error::DbError\">DbError</a>",synthetic:false,types:["syncstorage::db::error::DbError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"syncstorage/web/error/struct.HawkError.html\" title=\"struct syncstorage::web::error::HawkError\">HawkError</a>",synthetic:false,types:["syncstorage::web::error::HawkError"]},{text:"impl <a class=\"trait\" href=\"failure/trait.Fail.html\" title=\"trait failure::Fail\">Fail</a> for <a class=\"struct\" href=\"syncstorage/web/error/struct.ValidationError.html\" title=\"struct syncstorage::web::error::ValidationError\">ValidationError</a>",synthetic:false,types:["syncstorage::web::error::ValidationError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
