(function() {var implementors = {};
implementors["syncstorage"] = [{text:"impl <a class=\"trait\" href=\"syncstorage/db/util/_impl_from_sql_row_for_synctimestamp/diesel/query_source/trait.Table.html\" title=\"trait syncstorage::db::util::_impl_from_sql_row_for_synctimestamp::diesel::query_source::Table\">Table</a> for <a class=\"struct\" href=\"syncstorage/db/mysql/schema/batches/struct.table.html\" title=\"struct syncstorage::db::mysql::schema::batches::table\">table</a>",synthetic:false,types:["syncstorage::db::mysql::schema::batches::table"]},{text:"impl <a class=\"trait\" href=\"syncstorage/db/util/_impl_from_sql_row_for_synctimestamp/diesel/query_source/trait.Table.html\" title=\"trait syncstorage::db::util::_impl_from_sql_row_for_synctimestamp::diesel::query_source::Table\">Table</a> for <a class=\"struct\" href=\"syncstorage/db/mysql/schema/bso/struct.table.html\" title=\"struct syncstorage::db::mysql::schema::bso::table\">table</a>",synthetic:false,types:["syncstorage::db::mysql::schema::bso::table"]},{text:"impl <a class=\"trait\" href=\"syncstorage/db/util/_impl_from_sql_row_for_synctimestamp/diesel/query_source/trait.Table.html\" title=\"trait syncstorage::db::util::_impl_from_sql_row_for_synctimestamp::diesel::query_source::Table\">Table</a> for <a class=\"struct\" href=\"syncstorage/db/mysql/schema/collections/struct.table.html\" title=\"struct syncstorage::db::mysql::schema::collections::table\">table</a>",synthetic:false,types:["syncstorage::db::mysql::schema::collections::table"]},{text:"impl <a class=\"trait\" href=\"syncstorage/db/util/_impl_from_sql_row_for_synctimestamp/diesel/query_source/trait.Table.html\" title=\"trait syncstorage::db::util::_impl_from_sql_row_for_synctimestamp::diesel::query_source::Table\">Table</a> for <a class=\"struct\" href=\"syncstorage/db/mysql/schema/user_collections/struct.table.html\" title=\"struct syncstorage::db::mysql::schema::user_collections::table\">table</a>",synthetic:false,types:["syncstorage::db::mysql::schema::user_collections::table"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
